package com.github.bhaak;

import java.io.File;

/**
 * A FileFilter implementation that returns ebook files and directories.
 * 
 * @author Patric Mueller &lt;bhaak@gmx.net&gt;
 *
 */
public class BookFilter implements java.io.FileFilter {
	@Override
	public boolean accept(File file) {
		String filename = file.getName().toLowerCase();
		if (filename.endsWith(".epub") ||
			filename.endsWith(".fb2") ||
			filename.endsWith(".fb2.zip") ||
			(filename.endsWith(".txt") && !filename.endsWith(".bmk.txt")) || // skip bookmarks generated files
			filename.endsWith(".rtf") ||
			filename.endsWith(".html") ||
			filename.endsWith(".htm") ||
			filename.endsWith(".pdb") ||
			filename.endsWith(".mobi") ||
			filename.endsWith(".chm")) {
			return true;
		} else if (file.isDirectory()) {
			// ignore dictionaries directory
			if (filename.equals("dictionaries")) { return false; }

			// ignore sdr directories generated by Amazon's
			// standard reader
			return !filename.endsWith(".sdr");
		}
		return false;
	}
}